server:
  port: 8082

spring:
  application:
    name: my-application

  data:
    mongodb:
      uri: mongodb://localhost:27017/event-read-model

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: projector-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # We will deserialize the value as a simple String
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    security:
      oauth2:
        client:
          provider:
            keycloak:
              issuer-uri: ${KEYCLOAK_ISSUER_URI:http://host.docker.internal:8080/realms/event-ticketing}
          registration:
            # This client is used for M2M communication
            keycloak-m2m-client:
              provider: keycloak
              client-id: query-service-client
              client-secret: ${QUERY_SERVICE_CLIENT_SECRET} # Provide this via .env file
              authorization-grant-type: client_credentials
              scope: openid